version: "3"

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: easy_tec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - easy-tec-network

  # app:
  #   container_name: easy-tec-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   env_file:
  #     - .env
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/easy_tec?schema=public
  #   volumes:
  #     - ./src:/app/src
  #     - ./public:/app/public
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   networks:
  #     - easy-tec-network
    
volumes:
  postgres_data:

networks:
  easy-tec-network:
