version: "3"

services:
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: easy_tec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - easy-tec-network

volumes:
  postgres_data:

networks:
  easy-tec-network: