name: Build and deploy Node.js app to Azure Web App - easy-tec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # --- Configurar pnpm ---
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: '9.x'
          run_install: false

      # --- Instalar dependencias con pnpm ---
      - name: Install dependencies with pnpm
        run: pnpm install --no-frozen-lockfile


      # --- Construir la aplicación específica con Turborepo ---
      - name: Build the 'server' app with Turborepo
        run: pnpm run build --filter=server


      # --- Mover al directorio de la aplicación construida ---
      - name: Navigate to server build directory
        run: cd apps/server/dist


      # --- Zippear solo el contenido de la construcción del servidor ---
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: apps/server/dist


      # --- Subir el artefacto desde el directorio correcto ---
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: apps/server/dist/release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # --- Descomprimir en la raíz del directorio de trabajo del job de deploy ---
      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'easy-tec'
          slot-name: 'Production'
          package: . # Desplegar el contenido descomprimido
          startup-command: 'pnpm run start:prod'
